name: Build and deploy container app to Azure Web App - Userdatesting

on:
  push:
    branches:
      - main  # Adjust this if your deployment branch is different

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repository is fetched

      - name: Debug - Check Files
        run: ls -al  # Lists files to confirm Dockerfile is present

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: bugbustersktproject.azurecr.io  # Removed "https://"
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}

      - name: Build and Push Image to Azure Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bugbustersktproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/newbug-web:${{ github.sha }}
          file: ./Dockerfile  # Change this if Dockerfile is in a subdirectory

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: userdatesting
          slot-name: staging  # Change this if using production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: bugbustersktproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/newbug-web:${{ github.sha }}

